name = "free-palestine-counter"
main = "worker.js"
compatibility_date = "2026-09-19"

kv_namespaces = [
  { binding = "COUNTER", id = "e425a51d129842cf945597577072c1a6" }
]

routes = [
  { pattern = "freepalestine.win/api/count", zone_name = "freepalestine.win" }
]
